#!/bin/bash
function log {
    echo "$(date '+%Y/%m/%d %X') $*"
}

# Required for audio to work on Wayland, hooks into local pulse server.
if test -S "${XDG_RUNTIME_DIR//snap.$SNAP_NAME/pulse}"/native; then
    export PULSE_SERVER=unix:"${XDG_RUNTIME_DIR//snap.$SNAP_NAME/pulse}"/native
fi

# Change $HOME from numbered revision to symlinked current revision to prevent
# settings from breaking on every update. When verbose logs is enabled show
# snap information and disconnected interfaces.
export HOME="${HOME//$SNAP_REVISION/current}"
case "$@" in
    *-v*)
        log "[Snap]: Ludo version: $SNAP_VERSION"
        log "[Snap]: Snap revision: $SNAP_REVISION"
        log "[Snap]: Platform arch: $SNAP_ARCH"
        log "[Snap]: Session type: $XDG_SESSION_TYPE"
        for interface in desktop desktop-legacy wayland unity7 x11 opengl \
            network network-bind audio-playback joystick removable-media home; do
            if ! snapctl is-connected $interface; then
                log "[Snap]: Interface $interface is disconnected"
            fi
        done
        ;;
esac

# Set working dir to /data because assets, database and cores are searched in
# current path unless edited in ./ludo/settings.toml.
cd "$SNAP/data" || log "[Snap]: Failed to set working path"

# Execute Wayland binary when $WAYLAND_DISPLAY is set and fallback to X11 for
# everything else.
case "${WAYLAND_DISPLAY:+wayland}" in
    wayland)
        exec "$SNAP"/ludo-wayland "$@"
        ;;
    *)
        exec "$SNAP"/ludo-x11 "$@"
        ;;
esac
