#!/bin/bash
function log {
    echo "$(date '+%Y/%m/%d %X') $*"
}

# Required for audio to work on Wayland, hooks into local pulse server.
if test -S "${XDG_RUNTIME_DIR//snap.$SNAP_NAME/pulse}"/native; then
    export PULSE_SERVER=unix:"${XDG_RUNTIME_DIR//snap.$SNAP_NAME/pulse}"/native
fi

# Change $HOME from numbered revision to symlinked current revision to prevent
# settings from breaking on every update. When verbose logs is enabled show
# snap information and disconnected interfaces.
export HOME="${HOME//$SNAP_REVISION/current}"
case "$@" in
    *-v*)
        log "[Snap]: Ludo version: $SNAP_VERSION"
        log "[Snap]: Snap revision: $SNAP_REVISION"
        log "[Snap]: Platform arch: $SNAP_ARCH"
        for interface in desktop desktop-legacy wayland unity7 x11 opengl \
            network network-bind audio-playback joystick removable-media \
            config-ludo home; do
            if ! snapctl is-connected $interface; then
                log "[Snap]: Interface $interface is disconnected"
            fi
        done
        ;;
esac

# Move files to new locations and update dir paths in settings.
if test -d "$HOME"/.ludo && test ! -d "$HOME"/.local/share/ludo; then
    log "Updating file locations..."
    mkdir --parents "$HOME"/.local/share/ludo/
    mkdir --parents "$HOME"/.config/ludo/
    for f in "$HOME"/.ludo/*; do
        if test -d "$f"; then
            mv --no-clobber "$f" "$HOME"/.local/share/ludo/
        else
            if test "${f##*.}" == toml; then
                mv --no-clobber "$f" "$HOME"/.config/ludo/
            else
                mv --no-clobber "$f" "$HOME"/.local/share/ludo/
            fi
        fi    
    done
    sed --in-place "s|$HOME/.ludo|$HOME/.local/share/ludo|g" \
        "$HOME"/.config/ludo/settings.toml
    rm --dir "$HOME"/.ludo
fi

# Set working dir to /data because assets, database and cores are searched in
# current path unless edited in ./ludo/settings.toml.
cd "$SNAP/data" || log "[Snap]: Failed to set working path"

# Execute snap command
exec "$@"