name: ludo
summary: A minimalist front-end for Libretro emulators
description: |
  **Focus on playing**
  
  Ludo's user interface is distraction free and configuration is always optional.
  
  Scan your games and browse your collection categorized by system with playlists showing in-game screenshots.
  
  A contextual menu gives you access to actions and quick save / quick load anytime.
  
  We chose the best emulators for the job, configured with sane defaults guaranteeing a balance of speed and accuracy.

adopt-info: latest
base: core18
grade: stable
confinement: strict
architectures: 
  - build-on: amd64
  - build-on: arm64

plugs:
  config-ludo:
    interface: personal-files
    read:
    - $HOME/.ludo

apps:
  ludo:
    command: bin/wrapper ludo
    environment:
      LIBGL_DRIVERS_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
      DISABLE_WAYLAND: 1
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - opengl
      - network
      - network-bind
      - audio-playback
      - joystick
      - removable-media
      - config-ludo
      - home

parts:
  latest:
    plugin: nil
    override-build: |
      snapcraftctl build
      URL="https://api.github.com/repos/libretro/ludo/releases/latest"
      VERSION=$(curl --silent "$URL" | jq --raw-output .tag_name | cut -c 2-)
      snapcraftctl set-version "$VERSION"
      case $SNAPCRAFT_ARCH_TRIPLET in
        x86_64-linux-gnu)  ASSET="Ludo-Linux-x86_64-$VERSION.tar.gz";;
        aarch64-linux-gnu) ASSET="Ludo-Linux-arm-$VERSION.tar.gz";;
        *) echo "FATAL: UNKNOWN PLATFORM!"; exit 1;;
      esac
      curl --silent --location --output "$SNAPCRAFT_PART_INSTALL/$ASSET" \
        "https://github.com/libretro/ludo/releases/download/v$VERSION/$ASSET"
      tar --extract --strip-components=1 \
        --file="$SNAPCRAFT_PART_INSTALL/$ASSET" \
        --directory="$SNAPCRAFT_PART_INSTALL"
      rm -f "$SNAPCRAFT_PART_INSTALL/$ASSET"

    build-packages:
      - curl
      - tar
      - jq

    stage-packages:
      - libglu1-mesa
      - libopenal1
      - libpulse0
      - libgl1
      - libgl1-mesa-dri

    organize:
      ludo: bin/
      cores: data/cores/
      assets: data/assets/
      database: data/database/

  wrapper:
    source: scripts
    plugin: dump
    organize:
      wrapper: bin/wrapper